### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by kxxoling** [MrBlenny/react-flow-chart#3]
I tried to import this lib in a new `create-react-app --typescript` project but failed. I thought that may be something incompatible with `create-react-app` 2.1.8, so I clone the project and run `start:storybook` after `yarn` installed. It still failed with error `Type 'TouchEvent' is not assignable to type 'MouseEvent'.`

```
ERROR in /Users/windrunner/workspace/react-flow-chart/src/components/Canvas/Canvas.wrapper.tsx
./src/components/Canvas/Canvas.wrapper.tsx
[tsl] ERROR in /Users/windrunner/workspace/react-flow-chart/src/components/Canvas/Canvas.wrapper.tsx(40,49)
      TS2345: Argument of type 'DraggableEvent' is not assignable to parameter of type 'MouseEvent'.
  Type 'TouchEvent' is not assignable to type 'MouseEvent'.

ERROR in /Users/windrunner/workspace/react-flow-chart/src/components/Node/Node.wrapper.tsx
./src/components/Node/Node.wrapper.tsx
[tsl] ERROR in /Users/windrunner/workspace/react-flow-chart/src/components/Node/Node.wrapper.tsx(33,43)
      TS2345: Argument of type 'DraggableEvent' is not assignable to parameter of type 'MouseEvent'.
  Type 'TouchEvent' is missing the following properties from type 'MouseEvent': button, buttons, clientX, clientY, and 18 more.
ℹ ｢wdm｣: Failed to compile.
```

BTW, how can I use this in an existing non-TS project? It always failed to import `@mrblenny/react-flow-chart`. Can you provide a simple example on codesandbox or something like that?

**Comment by MrBlenny** [comment]
Yep, sorry about that. I'll look into the js dist over the next day or so.

**Comment by kxxoling** [comment]
@MrBlenny I believe there must be something different between our system configurations that caused the failure, because I checked out several git commits but all of them failed the same.

I have node v8.11.3 installed on my Mac which has newest macOS installed. `tsc --version` tolds me it is version 3.3.3333.

Anything else can I provide?

**Comment by kxxoling** [comment]
As I expected `rm -rf docs && yarn build:storybook` succeed as it shows error log like this:

```
yarn run v1.7.0
$ build-storybook -c config/storybook -o docs
info @storybook/react v4.0.0-alpha.24
info
info => Loading presets
info => Loading custom addons config.
info => Loading custom webpack config (full-control mode).
info Building storybook ...
ERR! Failed to build the storybook
ERR! /Users/windrunner/workspace/react-flow-chart/src/components/Canvas/Canvas.wrapper.tsx
ERR! ./src/components/Canvas/Canvas.wrapper.tsx
ERR! [tsl] ERROR in /Users/windrunner/workspace/react-flow-chart/src/components/Canvas/Canvas.wrapper.tsx(40,49)
ERR!       TS2345: Argument of type 'DraggableEvent' is not assignable to parameter of type 'MouseEvent'.
ERR!   Type 'MouseEvent<HTMLElement | SVGElement>' is missing the following properties from type 'MouseEvent': fromElement, layerX, layerY, movementX, and 22 more.
ERR! /Users/windrunner/workspace/react-flow-chart/src/components/Node/Node.wrapper.tsx
ERR! ./src/components/Node/Node.wrapper.tsx
ERR! [tsl] ERROR in /Users/windrunner/workspace/react-flow-chart/src/components/Node/Node.wrapper.tsx(33,43)
ERR!       TS2345: Argument of type 'DraggableEvent' is not assignable to parameter of type 'MouseEvent'.
ERR!   Type 'MouseEvent<HTMLElement | SVGElement>' is not assignable to type 'MouseEvent'.
info Building storybook completed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So it might be something about lint.

**Comment by MrBlenny** [comment]
Yep, I found out why the import was failing. I was not explicitly referring to `src/index.js` in the package.json `main` config. https://github.com/MrBlenny/react-flow-chart/commit/62942f3a3feeea7d10ee6158b2ca1c50dec6109a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R5

I've published `@mrblenny/react-flow-chart@0.0.3`. This includes updated `react` and `typescript` and a fix to the `package.json/main`. 

Here a demo:
https://codesandbox.io/s/4w46wv71o7

**Comment by kxxoling** [comment]
It works good in my demo as a requirement now, but I still cannot start storybook from the master branch code. Same issue as pasted before.

**Comment by MrBlenny** [comment]
Not quite sure about the second issue. Not quite sure where the `DraggableEvent` type is coming from.

Maybe it is related to using yarn instead of npm? I've tried on 2 computers now without any issue (npm with latest node, one on windows with wsl, one on mac). 

I'll close this for now.

**Comment by kxxoling** [comment]
@MrBlenny Actually I tried to figure out an "performance issue" last weekend, after some fruitless working, it disappeared after restarting of Chrome... 😭 

It's OK when installed by npm. No idea what's the difference.

**Comment by josh-peterson-bose** [comment]
@MrBlenny I'm running into this issue fyi

"don't use yarn" isn't really an easy solution if your ci/cd uses it
